name: Raise PR to Klavis mcp_servers

on:
  push:
    tags:
      - 'klavis.*'
    branches:
      - '**'
jobs:
  raise-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.KLAVIS_PR_TOKEN }}
      KLAVIS_REPO: klavis-ai/mcp_servers
      BRANCH_NAME: cashfree-mcp-${{ github.ref_name }}-pr
    steps:
      - name: Checkout cashfree-mcp
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "siva.durga:cashfree"
          git config --global user.email "siva.durga@cashfree.com"

      - name: Fork and clone Klavis mcp_servers
        run: |
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.actor }}/klavis.git 
          cd klavis
          git remote add upstream https://github.com/Klavis-AI/klavis.git
          git fetch upstream
          git checkout main || git checkout -b main
          git pull upstream main || true

      - name: Sync files to /mcp_servers/cashfree in forked repo
        run: |
          rm -rf klavis/mcp_servers/cashfree
          mkdir -p klavis/mcp_servers/cashfree
          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='smithery.yaml' \
            --exclude='server.json' \
            --exclude='klavis' \
            ./ klavis/mcp_servers/cashfree/ || [ $? -eq 24 ]

      - name: Create PR branch on fork
        run: |
          cd klavis/mcp_servers
          git checkout -b ${BRANCH_NAME}
          git add .
          git commit -m "Sync from cashfree-mcp tag ${{ github.ref_name }}"
          git push origin ${BRANCH_NAME}

      - name: Create or update Pull Request to upstream
        run: |
          gh pr list \
            --repo Klavis-AI/klavis \
            --head sivadurga-cashfree:cashfree-mcp-${{ github.ref_name }}-pr \
            --state open \
            --json url \
            --jq '.[0].url' > pr_url.txt
          PR_URL=$(cat pr_url.txt)
          if [ -z "$PR_URL" ]; then
            gh pr create \
              --repo Klavis-AI/klavis \
              --head sivadurga-cashfree:cashfree-mcp-${{ github.ref_name }}-pr \
              --base main \
              --title "[Automated] Sync from cashfree-mcp tag ${{ github.ref_name }}" \
              --body "Automated PR to sync changes from cashfree-mcp tag \`${{ github.ref_name }}\`."
          else
            echo "PR already exists: $PR_URL"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.KLAVIS_PR_TOKEN }}

